config/routes.rb
Wedding::Application.routes.draw do

   root 'page#index'
   resources :guestbooks
   get 'wedding_pictures'=> 'page#wedding_pictures', as: :wedding_pictures

end

app/models/guestbook.rb
class Guestbook < ActiveRecord::Base
	
	self.per_page = 5
	def approved?
		approved_at.present?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
	
	def index
		@admin = (params[:admin] == 'true')
		@guestbooks = Guestbook.paginate(:page => params[:page])
	end
	def show
	end

	def new
		@guestbook = Guestbook.new
	end

	def create
		@guestbook = Guestbook.new(guestbook_params)
		@guestbook.save
		flash[:notice]= 'Thank You for signing our guestbook.'
		redirect_to guestbooks_path 
	end
	def update
		@guestbook = Guestbook.find(params[:id])
		@guestbook.approved_at = Time.now.to_datetime
		@guestbook.save
		redirect_to guestbooks_path(admin: true), notice: "approved!"
	end

	def destroy
		@guestbook = Guestbook.find(params[:id])
		@guestbook.destroy
		redirect_to guestbooks_path(admin: true), notice: "Guestbook entery deleted"
	end


end
private

	def guestbook_params
		params.require(:guestbook).permit(:name, :message)
	end
	

app/controllers/page_controller.rb
class PageController < ApplicationController

  def index
  end

  def wedding_pictures
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
	def pretify(datetime)
		datetime.strftime('%b %e, %Y') if datetime
	end
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/guestbooks/_guestbook.html.haml
.guestbook-name= "#{g.name.titleize} | #{pretify(g.created_at)}"
.guestbook-msg= g.message

app/views/guestbooks/index.html.haml
.content
  .guestbook
    .bg
      .page.index 
        - if flash[:notice]
          .alert.alert-dismissible.alert-info
            = flash[:notice] 
        .row
          .col-md-6.col-md-offset-1
            %h2.text-right Guest book  
            - if @guestbooks.present?
              = will_paginate @guestbooks, class: 'text-right paginate'
              - @guestbooks.reverse.each do |g|
                - if @admin 
                  .well.text-container
                    .guestbook-name= "#{g.name.titleize} | #{pretify(g.created_at)}"
                    .guestbook-msg= g.message
                    .admin_actions
                      =link_to 'Delete', guestbook_path(g.id), method: :delete, class: 'btn btn-danger btn-xs'
                      =link_to 'Approve', guestbook_path(g.id), method: :put, class: 'btn btn-primary btn-xs', disabled: g.approved? 
                    .clearfix   
                - elsif g.approved?
                  .well.text-container
                    .guestbook-name= "#{g.name.titleize} | #{pretify(g.created_at)}"
                    .guestbook-msg= g.message
                .clearfix
              = will_paginate @guestbooks, class: 'text-right'  
              %br/
              %br/
              %br/
              %br/
          .clearfix  
    .clearfix

  .clearfix  

.clearfix
.br/
.br/

app/views/guestbooks/new.html.haml
.content
  .guestbook.page
    .bg
      .new.container
        .row
          .col-md-6
            %h2 Please Leave a note for the newlyweds!
            .well
              = form_for @guestbook, html: {multipart: true}  do |f|
                .form-group
                  =f.label :name
                  =f.text_field :name, class: 'form-control'
                .form-group
                  =f.label :message
                  =f.text_area :message, class: 'form-control', rows: '3'
                .form-group
                  .col-md-12
                    =f.submit "Sign Guestbook", class: 'btn btn-info'
                .clearfix
          .col-md-6
            .new
              .quote
                %h2 "This day I will marry my best friend,
                %h2 the one I laugh with, 
                %h2 live for, dream with, and love!  
                =link_to 'View Guest book', guestbooks_path, class: 'btn btn-info'

                

app/views/layouts/_music_player.html.haml
#music-player.jp-jplayer
#jp_container_1.jp-audio{"aria-label" => "media player", :role => "application"}
  .jp-type-single
    .jp-gui.jp-interface
      .jp-controls
        %i.fa.fa-play.jp-play{:role => "button", :tabindex => "0"} 
        %i.fa.fa-pause.jp-pause{:role => "button", :tabindex => "0"} 

:javascript

  $(function(){
    $('#music-player').jPlayer({
      ready: function(event){
        $(this).jPlayer("setMedia", {
          title: "Bubble",
          mp3: "/audio/wedding-song.mp3"
        }).jPlayer("play");
      },
      swfPath: "/swf/",
      supplied: "mp3",
      wmode: "window",
      useStateClassSkin: true,
      autoBlur: false,
      smoothPlayBar: true,
      keyEnabled: true,
      remainingDuration: true,
      toggleDuration: true,
      autoPlay: true,
      volume: 0.25
    });
  });

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          =link_to 'Home', "#{root_url}#home"
        %li
          =link_to 'Our Story', "#{root_url}#our-story"
        %li
          =link_to 'The Proposal', "#{root_url}#the-proposal"
        %li
          =link_to 'Wedding Party', "#{root_url}#wedding-party"
        %li
          =link_to 'Guestbook', new_guestbook_path
        %li
          =link_to 'Wedding Pictures', wedding_pictures_path, {style: "color: pink;"} 

      .navbar-right
        = render 'layouts/music_player' if !(controller_name == 'guestbooks') && !(controller_name == 'page' && action_name == 'wedding_pictures')
        
:javascript
  $('.nav li a').on('click', function() {
    $(this).parent().parent().find('li.active').removeClass('active');
    $(this).parent().addClass('active');
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>J&S Wedding Info</title>
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false %>
  <%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Wire+One|Ek+Mukta:200,400|Great+Vibes|Dawning+of+a+New+Day|Ubuntu+Mono|PT+Sans|Righteous|Indie+Flower|Raleway|Shadows+Into+Light+Two|Rock+Salt', media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <%= yield :head%>
</head>
<body>
	<%= render partial: 'layouts/nav'%>
	<%= yield %>

</body>
</html>

app/views/page/_home.html.haml
.row.hidden-xs.hidden-sm
  .col-md-offset-6
    .content
      .line1 Samra & Jawi
      .line2 got Married!!
      .line3 October 10th, 2015
  .row
    .col-sm-3.col-sm-offset-8
      .scroll-down
        =link_to 'Go to wedding video/pictures', wedding_pictures_path
.row
  .col-xs-5.hidden-md.hidden-lg.hidden-sm.mobil
    .line1 Samra & Jawi
    .line2 got Married!!
    .line3 October 10th, 2015
    =link_to 'Go to wedding video/pictures', wedding_pictures_path
.row
  .col-sm-6
  .col-sm-6.hidden-md.hidden-lg.hidden-xs
    .line1 Samra & Jawi
    .line2 got Married!!
    .line3 October 10th, 2015
    =link_to 'Go to wedding video/pictures', wedding_pictures_path
    
  
:javascript

  $(".line1, .line2, .line3").hide().each(function(i) {
    $(this).delay(i*800).fadeIn(800);
  });

app/views/page/_our_story.html.haml
%h1.text-center Our Story
.next.pull-right
  %h3 NEXT >>
.row
  .col-md-12.text-center.hidden-sm.hidden-xs
    .glyphicon.glyphicon-menu-left
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.1
    .glyphicon.glyphicon-option-horizontal  
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.2
    .glyphicon.glyphicon-option-horizontal  
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.3
    .glyphicon.glyphicon-option-horizontal  
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.4
    .glyphicon.glyphicon-option-horizontal    
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.5
    .glyphicon.glyphicon-option-horizontal  
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.6
    .glyphicon.glyphicon-option-horizontal  
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.7
    .glyphicon.glyphicon-option-horizontal  
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.8
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-heart.9
    .glyphicon.glyphicon-option-horizontal
    .glyphicon.glyphicon-menu-right 

.row
  .our-story-image.hidden-md.hidden-lg.container.mobile 
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i July 15, 2013
      %p The love story of Samra and Jawi started with a simple dinner at Mesale with Weyni and Meki (his cousin and her cousin). Introduced by the cousins these two hit it off right away and it was love at first site.

    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i July 22nd, 23rd and 24th
      %p First date at MKs was on July 22nd. The following day, they went out for a second date, where they watched the movie White House Down.  Third date however was at the kategna and Jazzamba where they sealed with first kiss. The two of them fell in love.  
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i July 25th, 2013
      %p Samra left for the USA with Jawi’s heart. As soon as Samra landed in the US, she got a new phone and downloaded viber and tango.  Needless to say, they were talking for hours dispite the time difference.  
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i September 13, 2013
      %p Samra returns to Addis for work. She was there for two weeks and the romance blossomed. 
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i October 14, 2013
      %p Jawi went to china and the love birds continued vibering and tangoing with 12 hr difference between them.
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i December 18th, 2013
      %p Samra surprises Jawi with a trip to Addis for the holidays and his birthday! Jawi introduces her to his dad and uncles. Samra introduces him to her mom and brothers 
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i January 10th 2014
      %p Samra returns to the US
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i February 18th, 2014
      %p As it was destined for the two to be together forever --Samra moves with a fabulous job to Addis!
    .col-xs-2
      .glyphicon.glyphicon-heart
    .col-xs-10
      %i November 24th 2014
      %p Jawi got down on one knee and asked for her hand in marriage. She said Yes!!  November 25th, 2014, Jawi and Samra left for the US so he can meet the rest of her family and friends. The big day is going to be on October 10th, 2015 and the love story continues...
  .row
    .col-sm-8.col-sm-offset-2.none-mobile
      .text1.text
        %h3.text-center July 15, 2013
        %p.text-center The love story of Samra and Jawi started with a simple dinner at Mesale with Weyni and Meki (his cousin and her cousin). Introduced by the cousins these two hit it off right away and it was love at first site. 
      .text2.text
        %h3.text-center July 22nd, 23rd and 24th
        %p.text-center First date at MKs was on July 22nd. The following day, they went out for a second date, where they watched the movie White House Down.  Third date however was at the kategna and Jazzamba where they sealed with first kiss. The two of them fell in love.  
      .text3.text
        %h3.text-center July 25, 2013
        %p.text-center Samra left for the USA with Jawi’s heart. As soon as Samra landed in the US, she got a new phone and downloaded viber and tango.  Needless to say, they were talking for hours dispite the time difference.
      .text4.text 
        %h3.text-center September 13, 2013
        %p.text-center Samra returns to Addis for work. She was there for two weeks and the romance blossomed.
      .text5.text 
        %h3.text-center October 14, 2013
        %p.text-center Jawi went to china and the love birds continued  vibering and tangoing with 12 hr difference between them.     
      .text6.text 
        %h3.text-center December 18, 2013
        %p.text-center Samra surprises Jawi with a trip to Addis for the holidays and his birthday! Jawi introduces her to his dad and uncles. Samra introduces him to her mom and brothers
      .text7.text 
        %h3.text-center January 10, 2014
        %p.text-center Samra returns to the US
      .text8.text 
        %h3.text-center February 18, 2014
        %p.text-center As it was destined for the two to be together forever --Samra moves with a fabulous job to Addis!
      .text9.text 
        %h3.text-center November 14, 2014
        %p.text-center Jawi got down on one knee and asked for her hand in marriage. She said YES!!.  November 25th, 2014, Jawi and Samra left for the US so he can meet the rest of her family and friends. The big day is going to be on October 10th, 2015 and the love story continues...       

:javascript
  $('.text1').show();
  $('.1').hover(
    function(){
      $('.text1').show();
    },
    function(){
      $('.text1').hide();
    });

  $('.2').hover(
    function(){
      $('.text2').show();
    },
    function(){
      $('.text2').hide();
    });

  $('.3').hover(
    function(){
      $('.text3').show();
    },
    function(){
      $('.text3').hide();
    });
  $('.4').hover(
    function(){
      $('.text4').show();
    },
    function(){
      $('.text4').hide();
    });
  $('.5').hover(
    function(){
      $('.text5').show();
    },
    function(){
      $('.text5').hide();
    });
  $('.6').hover(
    function(){
      $('.text6').show();
    },
    function(){
      $('.text6').hide();
    });
  $('.7').hover(
    function(){
      $('.text7').show();
    },
    function(){
      $('.text7').hide();
    });
  $('.8').hover(
    function(){
      $('.text8').show();
    },
    function(){
      $('.text8').hide();
    });   

  $('.9').hover(
    function(){
      $('.text9').show();
    },
    function(){
      $('.text9').hide();
    });           

  
      

app/views/page/_our_story2.html.haml
.hidden-md.hidden-lg.mobile
  %h1.text-center Our Story
  .text-center.instruction Swipe left or right 
.hidden-sm.hidden-xs
  %h1.text-center Our Story
  #right-arrow.pull-right.arrows
    %i.fa.fa-arrow-circle-o-right
  #left-arrow.pull-left.arrows
    %i.fa.fa-arrow-circle-o-left
.container
  #our-story-slideshow
    .keyframe
      %i July 15, 2013
      %p The love story of Samra and Jawi started with a simple dinner at Mesale with Weyni and Meki (his cousin and her cousin). Introduced by the cousins these two hit it off right away and it was love at first site.

    .keyframe
      %i July 22nd, 23rd and 24th, 2013
      %p First date was at MKs. The following day, they went out on their second date, where they watched the movie White House Down. On their third date Jawi took Samra to his favorite restaurant Kategna followed by live music at Jazzamba where they sealed the night with their first kiss. The two of them fell in love.
    
    .keyframe
      %i July 25th, 2013
      %p Samra left for the USA with Jawi’s heart. As soon as Samra landed in the US, she got a new phone and downloaded viber and tango.  Needless to say, they were talking for hours dispite the time difference.  

    .keyframe
      %i September 13, 2013
      %p Samra returns to Addis for work and their romance blossoms.
    
    .keyframe
      %i October 14, 2013
      %p Jawi went to china and the love birds continued vibering and tangoing with 12 hr difference between them.
      
    .keyframe
      %i December 18th, 2013
      %p Samra surprises Jawi with a trip to Addis for the holidays and his birthday! Jawi introduces her to his dad and uncles. Samra introduces him to her mom and brothers. 
      
    .keyframe
      %i January 10th 2014
      %p Samra returns to the U.S.
    
    .keyframe
      %i February 18th, 2014
      %p As it was destined for the two to be together forever --Samra moves with a fabulous job to Addis!
      
    .keyframe
      %i November 24th, 2014
      %p Jawi got down on one knees and asked for her hand in marriage. She said yes!! 
      
    .keyframe
      %i November 25th, 2014 
      %p Jawi and Samra left for the USA so he can meet the rest of her family and friends.  The big day is going to be October 10, 2015 and their love story continues……

    .keyframe
      %br/
      %br/
      %br/
      %i ~ THE END ~

:javascript
  $('#our-story-slideshow').slick({
    mobileFirst: true,
    nextArrow: '#our-story #right-arrow',
    prevArrow: '#our-story #left-arrow',
    infinite: false,
    dots: true
    
    // speed: 300,
    // slidesToShow: 1,
    // adaptiveHeight: false,
    // variableWidth: true
    
  });

app/views/page/_photo_gallery.html.haml
.hidden-md.hidden-lg
  .text-center.instruction Swipe left or right
/#outer{:style => "width: 80%; height: 80%; margin: 0 auto"}
#slideshow1{:style => "position: relative; top: 0px; left: 0px; width: 600px; height: 400px;"}
  / Slides Container
  %div{:style => "cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 600px; height: 400px;", :u => "slides"}
    %div= image_tag 'gallery/3x2/20141203_170552.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/Family-Pics.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/DSC_0900.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0003.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/IMG_0004.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/IMG_0362.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/20141214_115626.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/SP4.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/IMG_3894.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/DSC_1511.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0001.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0004.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/DSC_2082.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/DSC_2097.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/SP8.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0002.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0005.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/IMG_1261.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0006.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/IAF_7944.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/20141213_150329.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/Blue-Ridge-Pictures-140.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/IMG_0163.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/Samra&Jawi.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0008.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/scan0006.jpg', {u: 'image'}
    %div= image_tag 'gallery/3x2/Samra&jawi6.jpg', {u: 'image'}






  %span.jssora10l{:style => "top: 123px; left: 8px;", :u => "arrowleft"}
  
  %span.jssora10r{:style => "top: 123px; right: 8px;", :u => "arrowright"}


:javascript
  jQuery(document).ready(function ($) {
    
    var options = { 
      $AutoPlay: true,
      $ArrowNavigatorOptions: {
        $Class: $JssorArrowNavigator$,
        $ChanceToShow: 2,
        $AutoCenter: 2,
        $Steps: 1 
      } 
    };
    
    var jssor_slider1 = new $JssorSlider$('slideshow1', options);

    function ScaleSlider() {
      var parentWidth = $('#slideshow1').parent().width();
      if (parentWidth) {
        jssor_slider1.$ScaleWidth(parentWidth);
      }else{
        window.setTimeout(ScaleSlider, 30);
      }
    }
    //Scale slider after document ready
    ScaleSlider();
                                    
    //Scale slider while window load/resize/orientationchange.
    $(window).bind("load", ScaleSlider);
    $(window).bind("resize", ScaleSlider);
    $(window).bind("orientationchange", ScaleSlider);
  });

app/views/page/_venue.html.haml
.hotel-info{data: { top_bottom: 'background-color:rgba(0,0,0,0.9) ', bottom_center: 'background-color:rgba(255,0,0,0.0)'}} 
  %h1.text-center.page-title Venue Info
  %h1.text-center Hilton Hotel
  .address.text-center
    Menelik II Ave, 
    %br
    Addis Ababa 1164, Ethiopia
    %br
    +251 11 517 0000  
    
.row
  .col-md-8.col-md-offset-3.hidden-sm.hidden-xs
    .text-content{data: { bottom_top: 'transform:scale(1.5)', bottom_bottom: 'transform:scale(1)'}} 
      %h3 Samra Ashenafi 
      %h3 & 
      %h3 Dejen (Jawi) G/Kiros
      %span together with their families 
      %p request the honor of your presence as they join together in marriage on the evening of 
      .span.date Saturday October 10th, 2015. 
      %p The wedding reception will be held at the 
      .span.date Hilton Hotel, Addis Abeba, Ethiopia. 
      %h1 Invitation cards to follow 
    .clearfix

  .col-xs-12.hidden-md.hidden-lg
    .text-content-mobile
      .text-center
        %h3 Samra Ashenafi & Jawi Girma 
        %span together with their families 
        %p request the honor of your presence as they join together in marriage on the evening of 
        .span.date Saturday October 10th, 2015. 
        %p The wedding reception will be held at the 
        .span.date Hilton Hotel, Addis Abeba, Ethiopia.
        %h1 Invitation cards to follow 


    .clearfix
  .clearfix
.clearfix
%br/
%br/
%br/
.col-md-12.col-md-offset-5
  =link_to 'Sign their Guestbook', new_guestbook_path, class: 'btn btn-primary btn-lg sign-guestbook'
%br/
%br/
%br/
%br/
%br/

app/views/page/_wedding_pictures_1.html.haml
.slide= image_tag 'wedding-pictures-1/KOR_4396.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5328.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5357.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5374.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5390.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5406.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5416.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5481.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5490.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_52321.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5508.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5514.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5524.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5649.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5887.jpg'
.slide= image_tag 'wedding-pictures-1/KOR_5905.jpg'
.slide= image_tag 'wedding-pictures-1/KORA3783-2.jpg'
.slide= image_tag 'wedding-pictures-1/KORA3871-2.jpg'
.slide= image_tag 'wedding-pictures-1/KORA4104-2.jpg'
.slide= image_tag 'wedding-pictures-1/KORA4115-2.jpg'
.slide= image_tag 'wedding-pictures-1/KORA4153-2.jpg'
 





    




    

:javascript


  $(document).ready(function() {
    $.fn.fullpage({
        verticalCentered: true,
        resize : true,
        scrollingSpeed: 700,
        easing: 'easeInQuart',
        menu: false,
        navigation: false,
        navigationPosition: 'right',
        navigationTooltips: ['firstSlide', 'secondSlide'],
        slidesNavigation: true,
        slidesNavPosition: 'bottom',
        loopBottom: false,
        loopTop: false,
        loopHorizontal: true,
        autoScrolling: true,
        scrollOverflow: false,
        css3: false,
        paddingTop: '4em',
        paddingBottom: '10px',
        fixedElements: '#element1, .element2',
        normalScrollElements: '#element1, .element2',
        keyboardScrolling: true,
        touchSensitivity: 15,
        continuousVertical: false,
        animateAnchor: true,

        //events
        onLeave: function(index, direction){},
        afterLoad: function(anchorLink, index){},
        afterRender: function(){},
        afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){},
        onSlideLeave: function(anchorLink, index, slideIndex, direction){}
    });
  });

app/views/page/index.html.haml
/welcome page
.clear-fix.clearfix
.content
  .page.home#home
    = render partial: 'home'
  .page.our-story#our-story{data: { top_bottom: 'background-color:rgb(25,25,25) ', bottom_center: 'background-color:rgb(105,105,105)'}} 
    = render partial: 'our_story2'
  .page.proposal#the-proposal
    = render partial: 'proposal'
  .page.wedding-party#wedding-party
    = render partial: 'wedding_party'
  